/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Locale;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author yanukadeneth
 */
public class Login_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Login_GUI
     */
    Statement stmt;
    private final static Logger logr = Logger.getLogger(Logger.GLOBAL_LOGGER_NAME);

    public Login_GUI() {
        initComponents();

        //DB Connection
        try {
            DatabaseConnection dbcon = new DatabaseConnection();
            Connection con = DriverManager.getConnection(dbcon.GETDBURL(), dbcon.GETDBUSERNAME(), dbcon.GETDBPASSWORD());
            stmt = con.createStatement();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error : Database Connection Failed", JOptionPane.ERROR_MESSAGE);
            logr.log(Level.SEVERE, "Database Connection Failed", ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtbox_uname = new javax.swing.JTextField();
        passfield_pass = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_forgotpass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("GUI/Bundle"); // NOI18N
        setTitle(bundle.getString("Login_GUI.title")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Login_GUI.jPanel1.border.title"))); // NOI18N

        jLabel1.setText(bundle.getString("Login_GUI.jLabel1.text")); // NOI18N

        jLabel2.setText(bundle.getString("Login_GUI.jLabel2.text")); // NOI18N

        btn_login.setText(bundle.getString("Login_GUI.btn_login.text")); // NOI18N
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        btn_clear.setText(bundle.getString("Login_GUI.btn_clear.text")); // NOI18N
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_exit.setText(bundle.getString("Login_GUI.btn_exit.text")); // NOI18N
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_forgotpass.setBackground(new java.awt.Color(204, 204, 204));
        btn_forgotpass.setForeground(new java.awt.Color(0, 0, 255));
        btn_forgotpass.setText(bundle.getString("Login_GUI.btn_forgotpass.text")); // NOI18N
        btn_forgotpass.setBorder(null);
        btn_forgotpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_forgotpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(passfield_pass))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtbox_uname, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btn_login)
                        .addGap(18, 18, 18)
                        .addComponent(btn_clear)
                        .addGap(18, 18, 18)
                        .addComponent(btn_exit)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_forgotpass))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_clear, btn_exit, btn_login});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtbox_uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passfield_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_login)
                    .addComponent(btn_clear)
                    .addComponent(btn_exit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btn_forgotpass))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        txtbox_uname.setText("");
        passfield_pass.setText("");
        txtbox_uname.requestFocus();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed

        try {
            String qry = "select * from USERS";
            ResultSet rs = stmt.executeQuery(qry);

            String un = txtbox_uname.getText();
            String pw = String.valueOf(passfield_pass.getPassword());

            Locale loc;

            PassEncryption pe = new PassEncryption();

            String err = "Invalid Username or password";

            while (rs.next()) {
                String u = rs.getString(1);
                String p = rs.getString(3);

                int ut = rs.getInt(4);
                boolean resetpass = rs.getBoolean(6);

                boolean flag = false;

                if (un.equalsIgnoreCase(u)) {

                    logr.log(Level.INFO, "Attempted Login");

                    //New password if not exist
                    if (resetpass) {

                        logr.info(u + " : New Password Setup");

                        PasswordChange pc = new PasswordChange(u);
                        pc.setVisible(true);
                        this.dispose();
                        err = "Password Change in Progress";
                        break;
                    }

                    switch (rs.getInt(7)) {

                        case 2:
                            loc = new Locale("de", "DE");
                            break;
                        case 3:
                            loc = new Locale("fr", "FR");
                            break;
                        default:
                            loc = new Locale("en", "EN");
                            break;
                    }

                    if (PassEncryption.verifyUserPassword(pw, p, pe.GetSalt())) {

                        logr.info(u + " : Logged in Successfully");
                        flag = true;
                        switch (ut) {
                            case 1:
                                new Manager_GUI(u,loc).setVisible(true);
                                break;
                            default:
                                new Cashier_GUI(u,loc).setVisible(true);
                                break;
                        }
                        dispose();
                        err = "Welcome" + ", " + u;
                    }
                }

                if (flag) {
                    break;
                } else {
                    btn_clearActionPerformed(evt);
                }
            }

            JOptionPane.showMessageDialog(rootPane, err);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Please check all inputs and retry", "Error : Login Failed", JOptionPane.ERROR_MESSAGE);
            logr.log(Level.WARNING, "Login Failed : " + ex.getMessage());
        }

    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_forgotpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_forgotpassActionPerformed

        String u = txtbox_uname.getText();

        if (u.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please Enter a username to find hint", "Error : No Username", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            try {
                String qry = "SELECT * FROM USERS";
                ResultSet rs = stmt.executeQuery(qry);

                while (rs.next()) {
                    String udb = rs.getString(1);

                    if (u.equals(udb)) {
                        String hint = rs.getString(5);
                        JOptionPane.showMessageDialog(rootPane, "Password Hint : " + hint);
                        logr.fine(u + " : Viewed Hint");
                        break;
                    }
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Issue Retreiving the Forgot password. Please try again later", "Error : Could not load Forgot Password", JOptionPane.ERROR_MESSAGE);
                logr.log(Level.SEVERE, "Couldnt Load Forgot Password : " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btn_forgotpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        Logman lm = new Logman();
        lm.SetupLogger(logr);

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_GUI().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_forgotpass;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passfield_pass;
    private javax.swing.JTextField txtbox_uname;
    // End of variables declaration//GEN-END:variables
}
